### ISSUE TITLE
Huge docker image

### ISSUE THREAD

**Issue by larseggert** [private-octopus/picoquic-interop-runner#1]
Could you reorg your Dockerfile into multiple stages, to reduce the size of the image? See for example https://github.com/NTAP/quant/blob/master/Dockerfile.interop

**Comment by huitema** [comment]
The bulk of the load comes from the interop runner image loaded by the
script, and then loading the dependencies for ubuntu. I have no idea on
how to split that.

**Comment by huitema** [comment]
@larseggert I am looking at the docker file.

It starts from the network simulator endpoint image and installs 4 components:

1) Required packages (build-essential, git, cmake, libssl-dev, pkg-config)
2) Picotls 
3) Picoquic 
4) Run-endpoint script

For each of those, it copies an install script locally and runs it. For the dependencies, the script is a series of calls to apt-get. For picotls and picoquic, these are calls to git clone, cmake, and make. The script is just copied. This results in a set of subpackages which I do not fully understand. The main ones are:

* a large component, 250MB, which appears only when I build with "no-cache". I assume this is the ubuntu image with thepackages installed.
* picotls, 20MB
* picoquic, 250MB
* script. 5KB

I am all for shrinking that, but I dont quite get where to start...

**Comment by larseggert** [comment]
You should build in one image (=one FROM block), and then only copy installed files from the build to a new image (= a second FROM block.) This is what I do here: https://github.com/NTAP/quant/blob/master/Dockerfile.interop#L21-L22

Also see https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by huitema** [comment]
I think I got it working, using named steps. @larseggert can you check the new Dockerfile and see whether it looks correct?

**Comment by larseggert** [comment]
Looks good!
